name: Build Kiwi Next
on: push
# on: [workflow_call]

jobs:
  build:
    name: Build Kiwi Next
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [arm]
        # platform: [arm, arm64, x86, x64]
    
    steps:
      - name: CI workflow device configuration
        run: |
          df -h
          uname -a
          lscpu
          free -h

      - name: Reclaiming disk space on / by removing packages
        run: |
           echo "Free additional disk space on host"
           sudo apt purge -yq $(dpkg -l | grep '^ii' | awk '{ print $2 }' | grep -P '(cabal-|dotnet-|ghc-|gfortran-|postgresql-|mongodb-|mysql-|mssql-|libmono|php|aspnetcore)') nginx nodejs apache2 ant imagemagick powershell aria2 ansible shellcheck mono-runtime-common monodoc-manual ruby shellcheck zsync pollinate bazel firefox google-chrome-stable sphinxsearch subversion yarn snmp google-cloud-sdk 
           sudo apt autoremove -yq
           sudo apt-get autoclean

      - name: Show installed packages list
        run: apt list | grep "installed"

      - name: Reclaiming disk space on / by removing folders
        run: |
           sudo rm -rf /opt/hostedtoolcache /usr/local /usr/share/dotnet /usr/share/swift /opt/ghc
           sudo rm -rf "/usr/local/share/boost"
           sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Enabling i386 and updating APT repository
        run:  |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get upgrade -y
          
      - name: Drop fucking snaped Firefox after apt upgrade
        run: sudo snap remove --purge firefox

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 12288 # 12 GB
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-haskell: 'true'

      - name: Free space check
        run: |
          echo "Free space:"
          df -h

      - name: Installing Python and OpenJDK
        run: sudo apt install -y python2 openjdk-8-jdk-headless libncurses5 ccache
        
      - name: Create necessary folders
        run: sudo mkdir -p /usr/local/share/fonts
        
      - name: Install chromium deps tool
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $GITHUB_WORKSPACE/depot_tools
        
      - name: Download chromium source code
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          mkdir $GITHUB_WORKSPACE/chromium && cd $GITHUB_WORKSPACE/chromium
          fetch --nohooks --nohistory android
          
      - name: Install chromium build depends
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          cd $GITHUB_WORKSPACE/chromium/src
          
          echo "target_os = [ 'android' ]" >> ../.gclient
          gclient sync -D --no-history -v 
          build/install-build-deps.sh --android
          gclient runhooks
     
      - name: Free space check
        run: |
          echo "Free space:"
          df -h
     
      - name: Settings build config
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          cd $GITHUB_WORKSPACE/chromium/src
          
          mkdir -p out/Default
          
          cat <<EOF > out/Default/args.gn
          target_os = "android"
          target_cpu = "arm"
          is_component_build = false
          is_debug = false
          is_official_build = true
          symbol_level = 1
          disable_fieldtrial_testing_config = true
          dfmify_dev_ui = false
          disable_autofill_assistant_dfm = true
          disable_tab_ui_dfm = true
          ffmpeg_branding = "Chrome"
          proprietary_codecs = true
          is_cfi = true
          use_cfi_cast = true
          enable_gvr_services = false
          enable_remoting = false
          enable_reporting = false
          EOF

          gn gen out/Default

      - name: Build APK
        run: |
          autoninja -C out/Default chrome_public_apk -j 9
          
          ls out/Default
          ls out/Default/bin/chrome_public_apk
      
      - name: Free space check
        run: |
          echo "Free space:"
          df -h
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: Kiwi APK build
          path: out/Default/bin/
          retention-days: 7
