name: Build Kiwi Next
on: push
# on: [workflow_call]


jobs:
  build:
    name: Build Kiwi Next
    timeout-minutes: 1200
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [arm]
        # platform: [arm, arm64, x86, x64]
    
    steps:
      - name: CI workflow device configuration
        run: |
          df -h
          uname -a
          lscpu
          free -h

      - name: Check out files
        run: |
          cd $GITHUB_WORKSPACE/chromium/src/out/
          ls ./
          ls Default
          ls Default/bin/chrome_public_apk
          find "./" -type f -name "*.apk"
      
      - name: Free space check
        run: |
          echo "Free space:"
          df -h
          du -hs $GITHUB_WORKSPACE

