name: Build Kiwi Next
on: push
# on: [workflow_call]

jobs:
  build:
    name: Build Kiwi Next
    timeout-minutes: 1200
    runs-on: self-hosted
    
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        platform: [arm]
        # platform: [arm, arm64, x86, x64]
    
    steps:
      - name: CI workflow device configuration
        run: |
          df -h
          uname -a
          lscpu
          free -h

      - name: Enabling i386 and updating APT repository
        run:  |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get upgrade -y

      - name: Free space check
        run: |
          echo "Free space:"
          df -h

      - name: Installing Python and OpenJDK
        run: sudo apt install -y git python2 openjdk-8-jdk-headless libncurses5 ccache
        
      - name: Create necessary folders
        run: sudo mkdir -p /usr/local/share/fonts
        
      - name: Install chromium depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $GITHUB_WORKSPACE/depot_tools --depth 1
        
      - name: Download chromium source code
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          mkdir $GITHUB_WORKSPACE/chromium && cd $GITHUB_WORKSPACE/chromium

          fetch --nohooks --nohistory android
          
      - name: Install chromium build depends
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          cd $GITHUB_WORKSPACE/chromium/src
          
          echo "target_os = [ 'android' ]" >> ../.gclient
          gclient sync -D --no-history -v 
          build/install-build-deps.sh --android
          gclient runhooks
     
      - name: Free space check
        run: |
          echo "Free space:"
          df -h
     
      - name: Settings build config
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          cd $GITHUB_WORKSPACE/chromium/src
          
          mkdir -p out/Default
          
          cat <<EOF > out/Default/args.gn
          target_os = "android"
          target_cpu = "arm"
          is_component_build = false
          is_debug = false
          is_official_build = true
          symbol_level = 1
          disable_fieldtrial_testing_config = true
          dfmify_dev_ui = false
          disable_autofill_assistant_dfm = true
          disable_tab_ui_dfm = true
          ffmpeg_branding = "Chrome"
          proprietary_codecs = true
          is_cfi = true
          use_cfi_cast = true
          enable_gvr_services = false
          enable_remoting = false
          enable_reporting = false
          EOF

          gn gen out/Default

      - name: Build APK
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/depot_tools"  # TODO: fix
          cd $GITHUB_WORKSPACE/chromium/src
          
          autoninja -C out/Default chrome_public_apk -j 12
 
      - name: Check out files
        run: |
          ls out/Default
          ls out/Default/bin/chrome_public_apk
      
      - name: Free space check
        run: |
          echo "Free space:"
          df -h
      
      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: Kiwi APK build
          path: out/Default/bin/
          retention-days: 7
